### PR TITLE
Added Pry Gem

### PR DESCRIPTION
**Pull request by edwardheming**
Added Pry Gem and Better Errors Gem

### CODE REVIEW

**Comment by tylerpendleton** [comment]
I wrote some comments on your commits.  After you resolve those, we should merge the pull request.  Thanks Edward!

**Comment by tylerpendleton** [comment]
After you resolve that we can get this merged!

**Comment by edwardheming** [comment]
Revised Pry to remove hash rocket.

**Comment by edwardheming** [comment]
We want to be using Pry-Rails.

**Pull request merged**
